pipeline {
    agent any
    stages {
        stage('Clean') {
            steps {
                echo 'cleaning'
                bat 'mvn clean'
            }
        }
        stage('package') {
            steps{
                echo 'packaging...'
                bat 'mvn package'
            }
        }
          stage('build') {
            steps{
                echo 'building...'
                 bat 'mvn build'                    

            }
        }

    }
}
